version: '3'
services:
  tmf:
    image: denmor/tmf-server
    container_name: tmf-server
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
      - GAME_SETTINGS_FILE=${TMF_GAME_SETTINGS_FILE}
      - ADDITIONAL_OPTIONS=${TMF_ADDITIONAL_OPTIONS}
    ports:
      - ${TMF_PORT}:2350/tcp
      - ${TMF_PORT}:2350/udp
      - ${TMF_P2P_PORT}:3450/tcp
      - ${TMF_P2P_PORT}:3450/udp
    volumes:
      - ${TMF_GAME_DATA_DIR}:/tmf/GameData
      - ${TMF_GAME_LOGS_DIR}:/tmf/Logs
    networks:
      - trackmania_network

  xaseco:
    image: denmor/xaseco-server
    container_name: xaseco-server
    depends_on:
      - tmf
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
    volumes:
      - ${XASECO_CONFIG_DIR}:/xaseco/config_files
      - ${XASECO_LOG_DIR}:/xaseco/log_files
      - ${TMF_GAME_DATA_DIR}:/tmf/GameData
    networks:
      trackmania_network:
        ipv4_address: ${XASECO_IP}

networks:
  trackmania_network:
    ipam:
      driver: default
      config:
        - subnet: ${XASECO_SUBNET}
