version: '3'
services:
  tmf:
    image: denmor/tmf-server
    container_name: tmf-server
    environment:
      - LOCAL_UID=${LOCAL_UID}
      - LOCAL_GID=${LOCAL_GID}
      - GAME_SETTINGS_FILE=${GAME_SETTINGS_FILE}
      - ADDITIONAL_OPTIONS=${ADDITIONAL_OPTIONS}
    ports:
      - 2350:2350
      - 3450:3450
    volumes:
      - ${GAME_DATA_DIR}:/tmf/GameData
      - ${GAME_LOGS_DIR}:/tmf/Logs
