version: '2'
services:
  tmf:
    image: denmor/tmf-server
    container_name: tmf-server
    network_mode: host
    environment:
      - LOCAL_UID=1000
      - LOCAL_GID=1000
    ports:
      - 2350:2350
    volumes:
      - ./testdata:/tmf/GameData
      - ./testlogs:/tmf/Logs


